### PR TITLE
Reset password start

### PR DESCRIPTION
**Pull request by msecret**
This starts the basic of the reset password block, with the fields
and the "show my typing" link working.

### CODE REVIEW

**Comment by msecret** [comment]
screenshot_2015-07-31_12-39-12

**Comment by juliaelman** [comment]
LGTM

**Comment by maya** [comment]
I don't think this was complete @juliaelman. This still needs to add in password validation.

**Comment by juliaelman** [comment]
@maya yup! @msecret added a note in the comment and added a note to the Trello card here: https://trello.com/c/0tokNtJF/200-password-reset-block

Wanted to go ahead and move forward with this initial stage of work :)

**Pull request merged**
