### PR TITLE
Dropdowns

### PR DESCRIPTION
**Pull request by msecret**

### CODE REVIEW

**Comment by maya** [comment]
Same comment I left on the closed PR: https://github.com/18F/govt-wide-patternlibrary/pull/246#issuecomment-125777664

**Comment by msecret** [comment]
@maya I thought we said we were doing browser defaults?

Also: I don't think it's a good thing if the `<select>` with no classes added is broken, which is what is currently happening.

**Comment by maya** [comment]
Yes, we are using browser defaults on the dropdown items but the actual select element should match the style of our inputs.

**Comment by msecret** [comment]
Does that mean just to get a `<select>` working a class has to be added to it?

**Comment by maya** [comment]
Or we could apply that styling to the `<select>` element directly?

**Comment by maya** [comment]
Looking good visually. This does not need a fieldset, just a label and id on the select element.

**Comment by nickbristow** [comment]
@maya is correct. Fieldset is only necessary when you're adding extra instructions (legend) && grouping inputs.

**Comment by maya** [comment]
lgtm :+1:

**Pull request merged**
