### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by ErieMeyer**
Great catch @juliaelman -- updating the file here to go along with https://github.com/18F/govt-wide-patternlibrary/pull/66 and https://github.com/18F/govt-wide-patternlibrary/pull/65

### CODE REVIEW

**Comment by maya** [comment]
@ErieMeyer thanks for your contribution! Quick question: If this is just a page of text, do we need to create a jekyll collection? Basically, are you planning on breaking this out into partials? At the current state it looks like a single page, which is fine and can live on the site as is.

**Comment by ErieMeyer** [comment]
> Single page is fine! Thank you!

I can see a world where there are multiple languages that would need more pages, but for now, one is great.

**Comment by maya** [comment]
@ErieMeyer Also, @juliaelman just brought to my attention that all of our current pages are written in HTML, not markdown, while the components feeding in to the pages are in markdown. Would you rather this content be in markdown or HTML?

**Comment by maya** [comment]
@ErieMeyer actually leaning towards converting this to HTML. Would you like to do it or should we?

**Comment by ErieMeyer** [comment]
To make sure it's standard with the rest of the stuff you're doing, I would love if you took a run at it. Let me know if it's a pain, and I'll do it!

**Comment by juliaelman** [comment]
@ErieMeyer happy to help and done in #106! :boom: There are some comments and notes to address in there too.

**Comment by ErieMeyer** [comment]
Excellent -- thank you!!

🇺🇸🌷💯

**Pull request closed without merging**
