### PR TITLE
Add date fields

### PR DESCRIPTION
**Pull request by maya**
This adds the 3 text inputs for capturing dates. 

This is a simplified resolution to #239 

This resolves: #274

This is what it looks like:

screen shot 2015-08-06 at 10 13 29 pm

screen shot 2015-08-06 at 10 14 25 pm

### CODE REVIEW

**Comment by colinpmacarthur** [comment]
@maya: Looking good!

In the original GDS pattern, there aren't any up-down controls in each of the fields. They are just plain ol' text fields. Thoughts about why you included those controls here?

Thanks!

cc: @carodew @mollieru

**Comment by carodew** [comment]
@colinpmacarthur @maya – I believe it's the browser's default way to handle HTML5 number inputs. But it doesn't make sense for dates, definitely not years or dates (no one is going to click up 1979 times to get their birth year, for example). Is there a way of preventing the spinner controls from popping up?

**Comment by maya** [comment]
@carodew @colinpmacarthur sure, we can hide the up-down controls that appear on number inputs.

**Comment by maya** [comment]
@carodew @colinpmacarthur fixed here e18c690, d576a96.

This is what it looks like:
screen shot 2015-08-07 at 11 35 10 am

**Comment by juliaelman** [comment]
LGTM

**Comment by carodew** [comment]
lgtm2!

**Comment by colinpmacarthur** [comment]
lgtm3!

**Pull request merged**
