### PR TITLE
Adding font files and references

### PR DESCRIPTION
**Pull request by juliaelman**
This adds all of the font files for Source Sans Pro and creates a reference to them in the head.

### CODE REVIEW

**Comment by maya** [comment]
Looks good, @juliaelman. This adds regular and bold font (400 and 700 weight). This currently does not include italics. Can we verify with design if we need italics or other weights? https://www.google.com/fonts#UsePlace:use/Collection:Source+Sans+Pro cc @angel @mollieru

**Comment by angel** [comment]
I think we'll need at least 400 italics. We'll also need 600. That's what I've been using for the buttons. Thanks!

**Comment by maya** [comment]
Do we need 700?

**Comment by angel** [comment]
Yes, headers are in 700. If you think the page load will be too much, I would rather take out the 600 weight.

**Comment by maya** [comment]
We can try leaving it for now and if we feel it's too heavy, take it out. Although it would simplify things with only two weights, then we only have to declare normal and bold, rather than 400, 600, 700. Curious to hear other people's thoughts.

**Comment by maya** [comment]
On second thought, we might as well be explicit with our weights (i.e. 400 and 700, not normal and bold) in case other people want to extend this and add additional weights.

**Comment by mjovel** [comment]
@maya and @angel I think limiting to two weights might be prudent from a performance perspective. Maybe discussions of what a performance budget for the framework that comes with the pattern library should be? I would think this would be less than the average sites budget as content imagery and media by the frameworks user. That might make the decision easier to quantify?

**Comment by maya** [comment]
True, @mjovel. Also the last commit removes Source Code Pro, the monospace version of Source Sans Pro for this reason. We are using prism.css which uses `Consolas, Monaco, 'Andale Mono', monospace` as its monospace font stack which relies on browser fonts.

**Pull request merged**
